<script setup>
import { ref } from 'vue'
import { useToast } from '../composables/useToast'

const { toast } = useToast()

const reportTemplates = [
  { icon: 'bar-chart', name: 'Revenue Summary', desc: 'Revenue by client, project, and month with margin breakdown.', lastRun: 'Jul 18' },
  { icon: 'folder', name: 'Project Status', desc: "Snapshot of every project's health, progress, and owner.", lastRun: 'Jul 19' },
  { icon: 'truck', name: 'Vendor Performance', desc: 'On-time delivery, SLA adherence, and spend by vendor.', lastRun: 'Jul 15' },
  { icon: 'check-square', name: 'Time Tracking', desc: 'Hours logged per team member, project, and task type.', lastRun: 'Jul 17' },
  { icon: 'briefcase', name: 'Client Satisfaction', desc: 'Survey scores and sentiment trend by client and quarter.', lastRun: 'Jul 9' },
  { icon: 'shield', name: 'Audit Trail', desc: 'Full change history across projects, users, and permissions.', lastRun: 'Jul 11' }
]

const search = ref('')
const history = ref([
  { name: 'Revenue Summary', range: 'Jun 1 – Jun 30', by: 'RB', format: 'PDF', status: 'success' },
  { name: 'Project Status', range: 'As of Jul 19', by: 'System', format: 'XLSX', status: 'success' },
  { name: 'Vendor Performance', range: 'Q2 2026', by: 'JT', format: 'PDF', status: 'success' },
  { name: 'Time Tracking', range: 'Jul 1 – Jul 17', by: 'AS', format: 'CSV', status: 'warning' },
  { name: 'Audit Trail', range: 'Jul 1 – Jul 11', by: 'System', format: 'PDF', status: 'success' }
])

function generate(t) {
  toast({ title: `Generating "${t.name}"…`, status: 'running' })
  setTimeout(() => {
    history.value.unshift({ name: t.name, range: 'Just now', by: 'You', format: 'PDF', status: 'success' })
    toast({ title: `"${t.name}" is ready`, status: 'success' })
  }, 1200)
}

const filteredHistory = () => history.value.filter(h => h.name.toLowerCase().includes(search.value.toLowerCase()))
</script>

<template>
  <div class="flex items-center justify-between" style="margin-bottom: var(--space-6);">
    <div>
      <h1>Reports</h1>
      <p class="text-slate" style="margin-top:4px;">Generate and export reports across projects, vendors, and clients.</p>
    </div>
    <button class="btn btn-primary">
      <svg class="icon icon-sm"><use href="#icon-plus" /></svg>
      Custom Report
    </button>
  </div>

  <h3 style="margin-bottom: var(--space-4);">Report templates</h3>
  <div class="grid grid-3" style="margin-bottom: var(--space-8);">
    <div v-for="t in reportTemplates" :key="t.name" class="card">
      <svg class="icon icon-lg icon-signal"><use :href="`#icon-${t.icon}`" /></svg>
      <div class="card-title" style="margin-top:var(--space-3);">{{ t.name }}</div>
      <p class="text-sm" style="margin-top:var(--space-2);">{{ t.desc }}</p>
      <div class="flex items-center justify-between" style="margin-top:var(--space-4);">
        <span class="text-xs text-slate-soft">Last run: {{ t.lastRun }}</span>
        <button class="btn btn-secondary btn-sm" @click="generate(t)">Generate</button>
      </div>
    </div>
  </div>

  <div class="flex items-center justify-between" style="margin-bottom: var(--space-4);">
    <h3>Recently generated</h3>
    <label class="filter-search" style="max-width:260px;">
      <svg class="icon icon-sm icon-muted"><use href="#icon-search" /></svg>
      <input type="text" v-model="search" placeholder="Filter reports…">
    </label>
  </div>

  <div class="table-wrap">
    <table class="table-responsive">
      <thead><tr><th>Report</th><th>Range</th><th>Generated by</th><th>Format</th><th>Status</th><th></th></tr></thead>
      <tbody>
        <tr v-for="(h, i) in filteredHistory()" :key="i" :class="`status-${h.status}`">
          <td data-label="Report" style="font-weight:500;">{{ h.name }}</td>
          <td data-label="Range" class="text-sm">{{ h.range }}</td>
          <td data-label="Generated by">{{ h.by }}</td>
          <td data-label="Format"><span class="chip">{{ h.format }}</span></td>
          <td data-label="Status"><span class="badge" :class="`status-${h.status}`">{{ h.status === 'success' ? 'Ready' : 'Attention' }}</span></td>
          <td><button class="icon-button" aria-label="Download"><svg class="icon icon-sm"><use href="#icon-download" /></svg></button></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
